version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: kiyap-postgres
    environment:
      POSTGRES_DB: kiyap
      POSTGRES_USER: kiyap
      POSTGRES_PASSWORD: kiyap1234
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kiyap']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: kiyap-redis
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
